[FIX] add price_subtotal_signed to logos invoice analysis report
ingadhoc/patches pull request #20
Opened 2018-08-23 19:41 UTC by nicomacr

2018-08-23 23:41 UTC, jjscarafia requested changes

2018-08-23 23:41 UTC, jjscarafia commented on logos_invoice_analysis/report/logos_invoice_analysis.py
> +                         -("account_invoice_line"."price_subtotal_signed")
Nico, si no me equivoco "price_subtotal_signed" ya viene con negativo si es nota de credito, no haría falta el case, simplemente asignar este valor

2018-08-24 11:10 UTC, nicomacr commented on logos_invoice_analysis/report/logos_invoice_analysis.py
> +                         -("account_invoice_line"."price_subtotal_signed")
si es verdad, ahi lo corregi

2018-08-24 18:11 UTC, jjscarafia approved these changes

2018-08-24 18:11 UTC, merged